### ISSUE TITLE
Corrupted jclic.zip file if image not found when saving

### ISSUE THREAD

**Issue by ferrarimartin** [projectestac/jclic#26]
When saving a file to jclic.zip format by using JClic author, if there's a resource (for example, an image) that's missing, the target jclic.zip file starts being written, but when the resource would be saved, an error appears, writing stops at that point, and the output  zip file gets corrupted and can't be opened.
     This could happen if for example an image from a usb drive was included, and the drive removed before saving.
      It would be good if the behavior was less drastic, because if the user closes Jclic at that point, their work is lost.

**Comment by frncesc** [comment]
Class [edu.xtec.jclic.FileSystem#SecureFileOutputStream](https://github.com/projectestac/jclic/blob/master/src/core/edu/xtec/jclic/fileSystem/FileSystem.java#L523) has been modified to avoid this kind of errors. The original workflow when saving projects was:

__1__ - Create a temporary ZIP file
__2__ - Write the project definition (`.jclic` file) and needed ingredients (images, sounds...) into this temporary file.
__3__ - If something goes wrong, catch the exception and notify the user about the error found. The project state remains as "_unsaved_", and the original file has been not modified.
__4__ - From here, we assume that everything went well. The temporary ZIP file contains the saved project and is in good condition.
__5__ - Replace the original project file with the temporary ZIP file. This is done deleting the original file and, then, renaming the temporary.

In some cases, and for unknown reasons, the assertion made in step 4 is not met. Actually, the temporary file is corrupted and no error or exception has been thrown by the Java engine. This results in the loss of the original project.

Now, since [JClic v0.3.2.0](https://github.com/projectestac/jclic/releases/tag/v0.3.2.9), we perform an additional step:

__2b__ - Open the temporary file, read its the ZIP directory and check for empty or inaccessible files inside it. If something goes wrong, throw an [IOException](https://docs.oracle.com/javase/7/docs/api/java/io/IOException.html).

Hope this will reduce the risk of producing corrupted files when saving projects. Please notify us if the problem appears again.

Thanks for reporting!

**Comment by ferrarimartin** [comment]
Thank you so much Francesc.
I've added some missing translations for portuguese in launchpad, in case they are useful.
