### ISSUE TITLE
Arith2

### ISSUE THREAD

**Issue by manuelvi** [projectestac/jclic#28]
The "Arith2" module that generates always different mental calculation activities does not work correctly when it is exported to Html5 or SCORM and run in Moodle.
A concrete example is module 47 of the Higher Cycle of the activity is: https://clic.xtec.cat/projects/calculom/jclic.js/index.html
Thank you.

En español:
El módulo "Arith2" que genera actividades de cálculo mental siempre diferentes no funciona correctamente cuando se exporta a Html5 o a SCORM y se ejecutan en la Moodle.
Un ejemplo concreto es el módulo 47 del Ciclo Superior de la actividad es: https://clic.xtec.cat/projects/calculom/jclic.js/index.html
Gracias.

**Comment by manuelvi** [comment]
It seems that the error in Arith2 only appears in activities with decimals. In certain occasions they admit the point to indicate the decimal part and in other cases it requires the use of the comma.

En español:
Parece ser que el error en Arith2 solo aparece en las actividades con decimales. En determinadas ocasiones admiten el punto para indicar la parte decimal y en otros casos requiere del uso de la coma.

**Comment by frncesc** [comment]
I have solved three different problems in the new version 1.1.11 of [jclic.js](https://github.com/projectestac/jclic.js/releases/tag/v1.1.11), just published today:

- Some operations with decimal numbers and the "do not carry" option were incorrectly calculated. This bug has been fixed.
- A dot (".") was always used as a decimal separator, regardless of the user's local configuration. Now, in browsers configured in locales like Spanish, Catalan, French, Italian, Russian or German, a comma (",") will be used instead of a dot. Dot and coma are considered equivalent when evaluating student's responses, so both modes can be used indistinctly.
- Expressions like "0.1", "0.10" and "00,100" (with dot or comma) are now considered equivalent. _Arith_ activities will always convert text answers to numbers before checking.

Hope this will solve the detected problems with Arith in HTML5 activities. Thanks for reporting!

Español:
He solucionado tres problemas distintos en la nueva versión 1.1.11 de [jclic.js](https://github.com/projectestac/jclic.js/releases/tag/v1.1.11), que se acaba de publicar hace unos minutos:

- Algunas operaciones con la opción "sin llevar" y números decimales no se calculaban correctamente. Este error ha sido ya solucionado.
- _Arith_ siempre utilizaba el punto (".") como separador de decimales, independientemente de la configuración local del usuario. Ahora, cuando el navegador esté configurado en idiomas como español, catalán, francés, italiano, ruso o alemán se utilizará la coma (",") en lugar del punto. Ambos signos (punto y coma) se consideran equivalentes en el momento de evaluar las respuestas de los alumnos, de manera que pueden utilizar indistintamente el formato que prefieran.
- Expresiones como "0.1", "0.10" o "00,100" (con punto o coma) se consideran ahora equivalentes. Las actividades _Arith_ convertirán siempre las respuestas de texto a números antes de comprobarlas.

Espero que esto solucione los problemas detectados en Arith. ¡Gracias por reportarlos!
